/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernorAlphaABI } from "./GovernorAlphaABI";

export { GovernorAlphaABI__factory } from "./factories/GovernorAlphaABI__factory";
